version: 0.2
env:
  secrets-manager:
    BLACKDUCK_TOKEN: "arn:aws:secretsmanager:ap-northeast-1:947963676739:secret:BlackDuck_Token-652nLp:BlackDuck_Token"
  variables:
    BLACKDUCK_URL: "https://testing.blackduck.synopsys.com"
phases:
  pre_build:
    commands:
      - sudo apt-get update -y && sudo apt-get install cmake -y
      - sudo apt-get install python3-pip -y
      #- python --version #Python 3.9.17
  build:
    commands:
      - mkdir build && cd build
      - cmake ..
      - pip install blackduck-c-cpp
      - blackduck-c-cpp -bc "cmake --build ." -d . -s False -v True -proj Ueda_test -vers AWS_C_CPP -bd $BLACKDUCK_URL -a $BLACKDUCK_TOKEN -i False
