version: 0.2
env:
  secrets-manager:
    BLACKDUCK_TOKEN: "arn:aws:secretsmanager:ap-northeast-1:947963676739:secret:BlackDuck_Token-652nLp:BlackDuck_Token"
  parameter-store:
    BLACKDUCK_URL: "BlackDuck_url"
  variables:
    BLACKDUCK_PROJECT_NAME: "Ueda_test"
    BLACKDUCK_VERSION_NAME: "AWS"
phases:
  install:
    commands:
      - echo Synopsys detect installing 
      #- java -version    ##openjdk version "11.0.20" 2023-07-18 LTS
      - curl -LOk https://detect.synopsys.com/detect9.sh
      - chmod +x ./detect9.sh
  build:
    commands:
      - bash detect9.sh --blackduck.url=$BLACKDUCK_URL --blackduck.api.token=$BLACKDUCK_TOKEN --blackduck.trust.cert=true --detect.project.name=$BLACKDUCK_PROJECT_NAME --detect.project.version.name=$BLACKDUCK_VERSION_NAME --detect.source.path=. --blackduck.offline.mode=false --detect.excluded.detector.types=GIT
